server:
  port: 9010
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:{random.value}
    preferIpAddress: true
    
spring:
  application:
    name: user-cloud-gateway
    
    
    
    
#  cloud:
#    gateway:
#      routes:
#      - id:pet-two
#      uri: http://localhost:57903
#      predicates:
#      - Path=/api1/**

